version: 2.0
params:
  - name: artifactVersion #上传到云华产品仓的版本号
    value: "0.0.1"
  - name: taskName
    value: "buildOnlyWin"
env:
  label: Bitfun2Yellow_x64_vpc # 虚拟机标签，表示在哪台虚拟机执行，都写deveco_build
buildflows:
  - condition: taskName == "buildOnlyWin"
    jobs:
      - job: buildWin
        build_ref: .cloudbuild/buildWin.yml
        params:
          - name: buildVersion
            value: '${artifactVersion}_win'
  - condition: taskName == "buildWinAndLinux"
    jobs:
      - job: buildWin
        build_ref: .cloudbuild/buildWin.yml
        params:
          - name: buildVersion
            value: '${artifactVersion}_win'
      - job: buildLinux
        build_ref: .cloudbuild/buildLinux.yml
        params:
          - name: buildVersion
            value: '${artifactVersion}_linux'
  - condition: taskName == "buildOnlyLinux"
    jobs:
      - job: buildLinux
        build_ref: .cloudbuild/buildLinux.yml
        params:
          - name: buildVersion
            value: '${artifactVersion}_linux'
